name: Lint GitHub Actions workflows

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    uses: mozilla/actions/.github/workflows/actionlint.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6
    permissions:
      contents: read
      security-events: write # Required for zizmor to upload SARIF results
